feat: Add scaler and update repo (SC-16792)
maple-labs/mpl-migration pull request #20
Opened 2024-06-05 02:01 UTC by JGcarv

2024-06-05 10:19 UTC, 0xfarhaan requested changes

2024-06-05 10:19 UTC, 0xfarhaan commented on contracts/Migrator.sol
> +    uint256 public constant SCALER = 10;
let's make this immutable and set in the constructor please

2024-06-05 10:19 UTC, 0xfarhaan commented on contracts/Migrator.sol
> +    uint256 public constant SCALER = 10;
let's rename to TOKEN_SPLIT_SCALAR, scalar alone is too generic (also note the spelling with an A)

2024-06-05 10:19 UTC, 0xfarhaan commented on contracts/Migrator.sol
> +        uint256 outputAmount = amount_ * SCALER;
why not just calculate in the require statement as it's used once?

2024-06-05 10:19 UTC, 0xfarhaan commented on contracts/test/Migrator.t.sol
> +contract MigratorConstructorTest is Test {
Let's move this test folder and files out to have the repo reflect our current repos

2024-06-05 10:19 UTC, 0xfarhaan commented on contracts/test/Migrator.t.sol
> +import { IERC20 }    from "../../modules/erc20/contracts/interfaces/IERC20.sol";
import not used

2024-06-05 10:19 UTC, 0xfarhaan commented on contracts/Migrator.sol
>  contract Migrator {
Let's have this contract inherit the interface and update the IMigrator interface to include the new scalar parm

2024-06-06 10:37 UTC, 0xfarhaan reviewed
minor comments

2024-06-06 10:37 UTC, 0xfarhaan commented on tests/Migrator.t.sol
>          assertEq(migrator.newToken(), address(newToken));
we should assert the scalar

2024-06-06 10:37 UTC, 0xfarhaan commented on contracts/Migrator.sol
> +    uint256 public immutable override TOKEN_SPLIT_SCALAR;
nit if not constant we should lowercase and order based on type i.e `uint256` after `address`

2024-06-06 13:08 UTC, vbidin commented on contracts/Migrator.sol
> +    constructor(address oldToken_, address newToken_, uint256 scalar_) {
Can add a `require` for the scalar to be greater than zero.

2024-06-10 11:31 UTC, 0xfarhaan approved these changes

2024-06-10 11:34 UTC, merged